### PR TITLE
Update repos.json

### PR DESCRIPTION
**Pull request by TerslenK**
added my own repo SimpleNet

## Description
SimpleNet is a simple but realistic electric net

## Reason
I want to use this addon as a dependency on my other addons in the future, and im gonna make it public so others can use it aswell

### CODE REVIEW

**Comment by TerslenK** [comment]
https://github.com/TerslenK/SimpleNet

link for the repo

**Comment by TheBusyBiscuit** [comment]
The project is missing a license.

**Comment by TerslenK** [comment]
mb its added now

**Comment by TerslenK** [comment]
lets pretend this pr never opened

**Pull request closed without merging**
