### PR TITLE
Update repos.json

### PR DESCRIPTION
**Pull request by JasperChaseTOQ**
## Description
adding my first addon

## Reason
i want to add my addon to the list of addons

### CODE REVIEW

**Comment by FN-FAL113** [comment]
I only see empty classes in your repo specifically the items, they are non functional, addon will load but it doesn't have functional items?
Kinda early for an actual release but there are still a lot work needed in your side in providing a new content. This is an opinion based from what I'm seeing in your source code.

**Comment by JasperChaseTOQ** [comment]
i agree and actually i just was working on a new update which ill post tomorrow or tonight depending on when i fall asleep which will add a lot more items (over 20) and deletes a lot of the empty classes for now.

**Comment by JasperChaseTOQ** [comment]
updated it with new content and removed the empty classes

**Comment by FN-FAL113** [comment]
No worries though, I forgot there are no rules on this, just wait for biscuit on this.

**Comment by JasperChaseTOQ** [comment]
closing cause i want to work on it more and make it better first

**Pull request closed without merging**
