### PR TITLE
Fix bug in builds - latest DEV got marked as RC

### PR DESCRIPTION
**Pull request by WalshyDev**
## Description
966 got marked as release, fixed it

## Reason
People will get confused

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Any commit sha that has a matching tag will get marked as a release. Has always been that way, patching it here once afterwards won't change a thing.
Iirc it will get overridden on the next build anyway.

So perhaps an "ignore-tags: true" option would be a much better way to disable this for a repo/branch

**Comment by WalshyDev** [comment]
I mean, you just need to tag the correct commit on the stable branch :p 

What I did should have worked though, it removed the tag from the builds JSON which IIRC is where this loads from. Pretty sure it doesn't generate a new HTML each time. But, *shrug*

**Comment by TheBusyBiscuit** [comment]
Yeah but the builds.json is regenerated everytime.

**Comment by TheBusyBiscuit** [comment]
Nevermind, I am too lazy, I will just do this for now and worry later.

**Pull request closed without merging**
